//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Details
    {
        public Course_Details()
        {
            this.Student_Registration = new HashSet<Student_Registration>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public string total_duration { get; set; }
        public Nullable<double> total_fees { get; set; }
    
        public virtual ICollection<Student_Registration> Student_Registration { get; set; }
    }
}
