//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Payments
    {
        public int payment_id { get; set; }
        public Nullable<int> registration_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<double> payment_amount { get; set; }
        public string payement_mode { get; set; }
        public string payment_for { get; set; }
    
        public virtual Student_Registration Student_Registration { get; set; }
    }
}
