//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Qualification
    {
        public int qualification_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public string qualification { get; set; }
        public string university { get; set; }
        public Nullable<int> passing_year { get; set; }
        public Nullable<double> percentage { get; set; }
    
        public virtual Student_Details Student_Details { get; set; }
    }
}
