//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details
    {
        public Student_Details()
        {
            this.Student_Qualification = new HashSet<Student_Qualification>();
            this.Student_Registration = new HashSet<Student_Registration>();
        }
    
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> student_code { get; set; }
        public string email_address { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string local_address { get; set; }
    
        public virtual ICollection<Student_Qualification> Student_Qualification { get; set; }
        public virtual ICollection<Student_Registration> Student_Registration { get; set; }
    }
}
